services:
  app:
    # https://hub.docker.com/r/nibrev/nginx-iframe-proxy
    # https://github.com/rez0n/docker-nginx-iframe-proxy
    image: nibrev/nginx-iframe-proxy
    environment:
      - TOOLTYPE=dashboard
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/etc/nginx/html
    ports:
      - 9898:80
    restart: always
    logging:
      driver: "none"
